import React, { useState, useEffect } from 'react';
import Plot from 'react-plotly.js';
import { WidgetCard } from './WidgetCard';
import { CountryState, CyclePhase } from '../../types/worldEconomies';

// Visual constants
const PHASE_COLORS: Record<CyclePhase, string> = {
    'expansion': '#10b981', // Green
    'slowdown': '#f59e0b',  // Amber
    'recession': '#ef4444', // Red
    'recovery': '#3b82f6'   // Blue
};

type InfoTab = 'guide' | 'details' | 'metrics';

export const WorldEconomiesHealth: React.FC<{ id?: string }> = ({ id }) => {
    const [data, setData] = useState<CountryState[]>([]);
    const [loading, setLoading] = useState(true);
    const [selectedCountry, setSelectedCountry] = useState<CountryState | null>(null);
    const [activeTab, setActiveTab] = useState<InfoTab>('guide');

    useEffect(() => {
        loadData();
    }, []);

    useEffect(() => {
        if (selectedCountry) {
            setActiveTab('details');
        }
    }, [selectedCountry]);

    const loadData = async () => {
        setLoading(true);
        try {
            // Fetch from the static JSON generated by our python script
            const response = await fetch('/data/world_economies.json');
            if (!response.ok) throw new Error('Failed to load data');
            const jsonData: CountryState[] = await response.json();
            setData(jsonData);
        } catch (err) {
            console.error("Failed to load world economies data:", err);
            // Fallback or empty state could be handled here
        } finally {
            setLoading(false);
        }
    };

    // --- Prepare Plotly Traces ---

    // 1. Base Map (Dark) - handled by layout.geo

    // 2. Halos (Outer Glow) - Size based on Structural Risk
    const haloTrace: Partial<Plotly.Data> = {
        type: 'scattergeo',
        mode: 'markers',
        lat: data.map(d => d.lat),
        lon: data.map(d => d.lon),
        text: data.map(d => d.name),
        hoverinfo: 'skip', // Hover on core orb instead
        marker: {
            size: data.map(d => 15 + (d.structuralRisk / 3)), // 15 to ~48
            color: data.map(d => PHASE_COLORS[d.cyclePhase]),
            opacity: 0.2, // Faint glow
            symbol: 'circle',
            line: { width: 0 }
        },
        name: 'Risk Halo'
    };

    // 3. Core Orbs - Color by Phase, Opacity by Stress
    const orbTrace: Partial<Plotly.Data> = {
        type: 'scattergeo',
        mode: 'markers',
        lat: data.map(d => d.lat),
        lon: data.map(d => d.lon),
        text: data.map(d =>
            `${d.name}<br>` +
            `Phase: ${d.cyclePhase.toUpperCase()}<br>` +
            `Stress: ${d.stressLevel}/100<br>` +
            `Risk: ${d.structuralRisk}/100`
        ),
        hoverinfo: 'text',
        hovertemplate: '<b>%{text}</b><extra></extra>',
        marker: {
            size: 12, // Standard core size
            color: data.map(d => PHASE_COLORS[d.cyclePhase]),
            opacity: data.map(d => 0.6 + (d.stressLevel / 250)), // 0.6 to 1.0 (Higher stress = more solid)
            symbol: 'circle',
            line: {
                // Ring thickness based on External Vulnerability
                width: data.map(d => 1 + (d.externalVulnerability / 10)), // 1px to 11px
                color: '#ffffff'
            }
        },
        name: 'Economies'
    };

    return (
        <WidgetCard
            id={id}
            title="GLOBAL ECONOMIC MONITOR"
            tooltip="Real-time macroeconomic surveillance system."
            className="min-h-[600px]"
        >
            <div className="flex flex-col xl:flex-row gap-6 h-full">
                {/* Left: 3D Globe */}
                <div className="flex-1 relative h-[500px] xl:h-[600px] rounded-xl overflow-hidden bg-black border border-white/10 shadow-[inset_0_0_100px_rgba(0,0,0,1)] group">
                    {/* Deep Space Background */}
                    <div className="absolute inset-0 z-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-[#0B1221] via-[#020408] to-black"></div>
                    <div className="absolute inset-0 z-0 opacity-60"
                        style={{
                            backgroundImage: 'radial-gradient(white 1px, transparent 1px)',
                            backgroundSize: '50px 50px'
                        }}>
                    </div>

                    {loading ? (
                        <div className="absolute inset-0 flex items-center justify-center z-20">
                            <div className="flex flex-col items-center gap-4">
                                <div className="w-12 h-12 border-4 border-accent-cyan border-t-transparent rounded-full animate-spin shadow-[0_0_20px_rgba(34,211,238,0.5)]"></div>
                                <div className="text-accent-cyan font-mono text-sm tracking-[0.2em] animate-pulse">ESTABLISHING UPLINK...</div>
                            </div>
                        </div>
                    ) : (
                        <Plot
                            data={[haloTrace, orbTrace]}
                            layout={{
                                geo: {
                                    showframe: false,
                                    showcoastlines: true,
                                    coastlinecolor: '#334155',
                                    projection: {
                                        type: 'orthographic',
                                        rotation: { lon: 10, lat: 10 } // Initial view
                                    },
                                    bgcolor: 'rgba(0,0,0,0)',
                                    showland: true,
                                    landcolor: '#0f172a', // Dark slate land
                                    showocean: true,
                                    oceancolor: 'rgba(0,0,0,0)', // Transparent ocean to see background
                                    showlakes: false,
                                    showcountries: true,
                                    countrycolor: '#1e293b',
                                    lonaxis: { showgrid: true, gridcolor: '#1e293b', gridwidth: 0.5 },
                                    lataxis: { showgrid: true, gridcolor: '#1e293b', gridwidth: 0.5 },
                                },
                                paper_bgcolor: 'rgba(0,0,0,0)',
                                plot_bgcolor: 'rgba(0,0,0,0)',
                                margin: { l: 0, r: 0, t: 0, b: 0 },
                                showlegend: false,
                                hoverlabel: {
                                    bgcolor: '#0f172a',
                                    bordercolor: '#334155',
                                    font: { color: '#ffffff', family: 'monospace' }
                                }
                            }}
                            style={{ width: '100%', height: '100%' }}
                            config={{ displayModeBar: false, scrollZoom: true }}
                            onClick={(event) => {
                                const point = event.points[0];
                                // Match by index since we mapped directly
                                if (point && point.pointIndex !== undefined) {
                                    const country = data[point.pointIndex];
                                    if (country) setSelectedCountry(country);
                                }
                            }}
                        />
                    )}

                    {/* HUD Overlay */}
                    <div className="absolute top-6 left-6 z-10 pointer-events-none">
                        <div className="backdrop-blur-md bg-black/60 border border-white/10 rounded-lg p-4 shadow-[0_0_30px_rgba(0,0,0,0.8)] border-l-4 border-l-accent-cyan">
                            <div className="flex items-center gap-3 mb-2">
                                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse shadow-[0_0_10px_rgba(34,197,94,0.8)]"></div>
                                <span className="text-white text-xs font-display uppercase tracking-widest">Live Feed</span>
                            </div>
                            <div className="text-[10px] text-text-muted font-mono space-y-1">
                                <div className="flex justify-between gap-4"><span>NODES:</span> <span className="text-accent-cyan">{data.length} ACTIVE</span></div>
                                <div className="flex justify-between gap-4"><span>SYNC:</span> <span className="text-white">T-00:00:00</span></div>
                            </div>
                        </div>
                    </div>

                    {/* Legend */}
                    <div className="absolute bottom-6 left-6 z-10 pointer-events-none">
                        <div className="backdrop-blur-md bg-black/60 border border-white/10 rounded-lg p-4 shadow-[0_0_30px_rgba(0,0,0,0.8)]">
                            <h4 className="text-text-muted text-[10px] font-mono uppercase tracking-widest mb-3 border-b border-white/10 pb-2">Cycle Phase</h4>
                            <div className="space-y-2">
                                {Object.entries(PHASE_COLORS).map(([phase, color]) => (
                                    <div key={phase} className="flex items-center gap-3">
                                        <div className="w-2 h-2 rounded-full shadow-[0_0_8px_currentColor]" style={{ backgroundColor: color, color: color }}></div>
                                        <span className="text-[10px] text-white font-mono uppercase opacity-80">{phase}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Right: Analysis Panel */}
                <div className="xl:w-96 flex flex-col gap-4 h-[600px]">
                    {/* Tab Navigation */}
                    <div className="flex bg-[#0B1221] border border-white/10 rounded-lg p-1">
                        <button onClick={() => setActiveTab('guide')} className={`flex-1 py-2 text-[10px] font-bold uppercase tracking-wider rounded transition-all ${activeTab === 'guide' ? 'bg-white/10 text-white shadow-glow-sm' : 'text-text-muted hover:text-white'}`}>Manual</button>
                        <button onClick={() => setActiveTab('details')} className={`flex-1 py-2 text-[10px] font-bold uppercase tracking-wider rounded transition-all ${activeTab === 'details' ? 'bg-white/10 text-white shadow-glow-sm' : 'text-text-muted hover:text-white'}`}>Analysis</button>
                        <button onClick={() => setActiveTab('metrics')} className={`flex-1 py-2 text-[10px] font-bold uppercase tracking-wider rounded transition-all ${activeTab === 'metrics' ? 'bg-white/10 text-white shadow-glow-sm' : 'text-text-muted hover:text-white'}`}>Metrics</button>
                    </div>

                    {/* Panel Content */}
                    <div className="bg-[#0B1221] border border-white/10 rounded-lg flex-1 overflow-y-auto custom-scrollbar relative shadow-[0_0_30px_rgba(0,0,0,0.3)]">

                        {/* GUIDE TAB */}
                        {activeTab === 'guide' && (
                            <div className="p-6 space-y-6 animate-fade-in">
                                <div>
                                    <h3 className="text-lg font-display text-white mb-2">Visual Decoding</h3>
                                    <div className="h-0.5 w-12 bg-accent-cyan mb-4"></div>
                                    <p className="text-xs text-text-secondary leading-relaxed">
                                        Each node represents a national economy. Its visual properties encode real-time macroeconomic stress and cycle positioning.
                                    </p>
                                </div>
                                <div className="space-y-4">
                                    <div className="p-3 bg-white/5 rounded border border-white/5">
                                        <div className="text-xs font-bold text-white mb-1">Core Color</div>
                                        <p className="text-[10px] text-text-muted">Indicates the current Business Cycle Phase (Expansion, Slowdown, Recession, Recovery).</p>
                                    </div>
                                    <div className="p-3 bg-white/5 rounded border border-white/5">
                                        <div className="text-xs font-bold text-white mb-1">Halo Size</div>
                                        <p className="text-[10px] text-text-muted">Proportional to <span className="text-white">Structural Risk</span> (Debt, Deficits, Inflation).</p>
                                    </div>
                                    <div className="p-3 bg-white/5 rounded border border-white/5">
                                        <div className="text-xs font-bold text-white mb-1">Outer Ring Thickness</div>
                                        <p className="text-[10px] text-text-muted">Indicates <span className="text-white">External Vulnerability</span> (FX reserves, Terms of Trade).</p>
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* DETAILS TAB */}
                        {activeTab === 'details' && (
                            <div className="p-6 space-y-6 animate-fade-in">
                                {selectedCountry ? (
                                    <>
                                        <div className="flex justify-between items-start">
                                            <div>
                                                <div className="text-[10px] font-mono text-accent-cyan mb-1">TARGET LOCKED</div>
                                                <h2 className="text-3xl font-display text-white">{selectedCountry.name}</h2>
                                                <div className="inline-block px-2 py-0.5 rounded bg-white/10 text-[10px] font-mono text-text-muted mt-2">
                                                    ISO: {selectedCountry.isoCode}
                                                </div>
                                            </div>
                                            <div className="text-right">
                                                <div className="text-4xl font-mono text-white font-bold tracking-tighter">{selectedCountry.stressLevel}</div>
                                                <div className="text-[10px] text-text-muted uppercase tracking-widest">Stress Index</div>
                                            </div>
                                        </div>

                                        <div className="p-4 bg-white/5 rounded border border-white/10">
                                            <div className="text-xs text-text-muted uppercase tracking-widest mb-2">Cycle Phase</div>
                                            <div className="text-lg font-medium text-white flex items-center gap-2">
                                                <span className="w-2 h-2 rounded-full" style={{ backgroundColor: PHASE_COLORS[selectedCountry.cyclePhase] }}></span>
                                                {selectedCountry.cyclePhase.toUpperCase()}
                                            </div>
                                            <div className="mt-2 text-[10px] text-text-secondary">
                                                Momentum: <span className={selectedCountry.cycleMomentum > 0 ? 'text-positive' : 'text-negative'}>
                                                    {selectedCountry.cycleMomentum > 0 ? 'Accelerating' : 'Decelerating'} ({selectedCountry.cycleMomentum})
                                                </span>
                                            </div>
                                        </div>

                                        <div className="space-y-3">
                                            <h4 className="text-xs font-bold text-white uppercase tracking-wider border-b border-white/10 pb-2">Risk Profile</h4>

                                            <div className="space-y-1">
                                                <div className="flex justify-between text-xs">
                                                    <span className="text-text-secondary">Structural Risk</span>
                                                    <span className="text-white font-mono">{selectedCountry.structuralRisk}/100</span>
                                                </div>
                                                <div className="w-full bg-white/10 h-1 rounded-full overflow-hidden">
                                                    <div className="bg-amber-500 h-full" style={{ width: `${selectedCountry.structuralRisk}%` }}></div>
                                                </div>
                                            </div>

                                            <div className="space-y-1">
                                                <div className="flex justify-between text-xs">
                                                    <span className="text-text-secondary">External Vulnerability</span>
                                                    <span className="text-white font-mono">{selectedCountry.externalVulnerability}/100</span>
                                                </div>
                                                <div className="w-full bg-white/10 h-1 rounded-full overflow-hidden">
                                                    <div className="bg-red-500 h-full" style={{ width: `${selectedCountry.externalVulnerability}%` }}></div>
                                                </div>
                                            </div>

                                            <div className="space-y-1">
                                                <div className="flex justify-between text-xs">
                                                    <span className="text-text-secondary">Instability Risk</span>
                                                    <span className="text-white font-mono">{selectedCountry.instabilityRisk}/100</span>
                                                </div>
                                                <div className="w-full bg-white/10 h-1 rounded-full overflow-hidden">
                                                    <div className="bg-purple-500 h-full" style={{ width: `${selectedCountry.instabilityRisk}%` }}></div>
                                                </div>
                                            </div>
                                        </div>
                                    </>
                                ) : (
                                    <div className="h-full flex flex-col items-center justify-center text-center text-text-muted space-y-4 opacity-60">
                                        <div className="w-16 h-16 rounded-full border border-dashed border-white/20 flex items-center justify-center animate-pulse-slow">
                                            <span className="text-2xl">⊕</span>
                                        </div>
                                        <div>
                                            <p className="text-sm font-mono text-white">NO TARGET SELECTED</p>
                                            <p className="text-xs mt-1">Click a node on the globe to initiate analysis.</p>
                                        </div>
                                    </div>
                                )}
                            </div>
                        )}

                        {/* METRICS TAB */}
                        {activeTab === 'metrics' && (
                            <div className="p-6 space-y-6 animate-fade-in">
                                {selectedCountry && selectedCountry.metrics ? (
                                    <>
                                        <div>
                                            <h3 className="text-lg font-display text-white mb-1">{selectedCountry.name}</h3>
                                            <p className="text-xs text-text-muted font-mono">Macro Telemetry</p>
                                        </div>

                                        <div className="grid grid-cols-2 gap-4">
                                            <div className="p-3 bg-white/5 rounded border border-white/5">
                                                <div className="text-[10px] text-text-muted uppercase">GDP Growth</div>
                                                <div className={`text-lg font-mono font-bold ${selectedCountry.metrics.gdpGrowth! > 0 ? 'text-positive' : 'text-negative'}`}>
                                                    {selectedCountry.metrics.gdpGrowth}%
                                                </div>
                                            </div>
                                            <div className="p-3 bg-white/5 rounded border border-white/5">
                                                <div className="text-[10px] text-text-muted uppercase">Inflation</div>
                                                <div className={`text-lg font-mono font-bold ${selectedCountry.metrics.inflation! > 5 ? 'text-negative' : 'text-white'}`}>
                                                    {selectedCountry.metrics.inflation}%
                                                </div>
                                            </div>
                                            <div className="p-3 bg-white/5 rounded border border-white/5">
                                                <div className="text-[10px] text-text-muted uppercase">Unemployment</div>
                                                <div className="text-lg font-mono font-bold text-white">
                                                    {selectedCountry.metrics.unemployment}%
                                                </div>
                                            </div>
                                            <div className="p-3 bg-white/5 rounded border border-white/5">
                                                <div className="text-[10px] text-text-muted uppercase">Debt/GDP</div>
                                                <div className={`text-lg font-mono font-bold ${selectedCountry.metrics.debtToGdp! > 90 ? 'text-warning' : 'text-white'}`}>
                                                    {selectedCountry.metrics.debtToGdp}%
                                                </div>
                                            </div>
                                        </div>

                                        <div className="mt-4">
                                            <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-2">Behavioral Signal</h4>
                                            <div className="flex items-center gap-4">
                                                <div className="flex-1 h-2 bg-white/10 rounded-full overflow-hidden relative">
                                                    <div className="absolute left-1/2 top-0 bottom-0 w-0.5 bg-white/50"></div>
                                                    {/* Map -1 to 1 range to 0 to 100% */}
                                                    <div
                                                        className={`h-full absolute top-0 bottom-0 w-2 rounded-full ${selectedCountry.behavioralSignal > 0 ? 'bg-negative' : 'bg-positive'}`}
                                                        style={{
                                                            left: `${((selectedCountry.behavioralSignal + 1) / 2) * 100}%`,
                                                            transform: 'translateX(-50%)'
                                                        }}
                                                    ></div>
                                                </div>
                                                <div className="text-xs font-mono text-white w-12 text-right">{selectedCountry.behavioralSignal}</div>
                                            </div>
                                            <div className="flex justify-between text-[10px] text-text-muted mt-1">
                                                <span>Optimistic</span>
                                                <span>Fearful</span>
                                            </div>
                                        </div>
                                    </>
                                ) : (
                                    <div className="h-full flex flex-col items-center justify-center text-center text-text-muted space-y-4 opacity-60">
                                        <div className="w-16 h-16 rounded-full border border-dashed border-white/20 flex items-center justify-center animate-pulse-slow">
                                            <span className="text-2xl">📊</span>
                                        </div>
                                        <div>
                                            <p className="text-sm font-mono text-white">NO METRICS AVAILABLE</p>
                                        </div>
                                    </div>
                                )}
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </WidgetCard>
    );
};
