"""
Phase Transition Visualization
==============================

Goal: Visualize the "General Rule" of Structural Risk as a Phase Transition.
The relationship between ASF (Fragility) and Risk is not static; it depends on the "Basal Connectivity" (System Integration).

We will generate a 3D Surface Plot:
- X-axis: ASF (Structural Fragility)
- Y-axis: Basal Correlation (System Connectivity)
- Z-axis: Predicted Risk (Forward Drawdown)

This will show the "Twisted Surface" where the slope of Risk/ASF flips sign as Connectivity crosses a critical threshold.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import os

OUTPUT_DIR = r"c:\key\wise_adviser_cursor_context\Caria_repo\caria\docs\research\outputs"

def load_and_model():
    # Load the data generated by prove_regime_theory.py
    data_path = os.path.join(OUTPUT_DIR, 'Table_Theory_Data.csv')
    if not os.path.exists(data_path):
        print("Data not found. Please run prove_regime_theory.py first.")
        return
    
    df = pd.read_csv(data_path, index_col=0, parse_dates=True)
    
    # Simple Interaction Model (Use pre-calculated coefficients from Model 2 for cleaner surface)
    # Risk ~ alpha + b1*ASF + b2*Basal + b3*(ASF*Basal)
    
    # Approximate coefficients from regression log (Model 2)
    # const: 0.0196
    # ASF: 0.3843
    # Basal: -0.0666
    # Interaction: -1.5614
    
    coeffs = {
        'const': 0.0196,
        'ASF': 0.3843,
        'Basal': -0.0666,
        'Inter': -1.5614
    }
    
    return df, coeffs

def plot_surface(df, coeffs):
    # Create Grid
    asf_range = np.linspace(df['ASF'].min(), df['ASF'].max(), 50)
    basal_range = np.linspace(df['Basal_Corr'].min(), df['Basal_Corr'].max(), 50)
    
    X, Y = np.meshgrid(asf_range, basal_range)
    
    # Calculate Z (Predicted Risk)
    # Center the interaction term as done in regression: (ASF * Basal) - Mean(ASF*Basal)
    # To keep it simple for viz, we'll just use the raw interaction structure:
    # Risk = const + b1*A + b2*B + b3*(A*B - mean_product)
    
    mean_prod = (df['ASF'] * df['Basal_Corr']).mean()
    
    Z = (coeffs['const'] + 
         coeffs['ASF'] * X + 
         coeffs['Basal'] * Y + 
         coeffs['Inter'] * (X * Y - mean_prod))
    
    # Plot
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(111, projection='3d')
    
    # Surface
    surf = ax.plot_surface(X, Y, Z, cmap='viridis', alpha=0.8, edgecolor='none')
    
    # Labels
    ax.set_xlabel('ASF (Structural Fragility)')
    ax.set_ylabel('Basal Connectivity (Mean Corr)')
    ax.set_zlabel('Predicted Crisis Risk')
    ax.set_title('The General Rule: Connectivity-Dependent Phase Transition\n(Risk varies with ASF, but the SLOPE depends on Connectivity)')
    
    # Annotate Regimes
    # 90s (Low Connectivity)
    ax.text(df['ASF'].mean(), df['Basal_Corr'].min(), Z.max(), "Zone 1: Contagion\n(Low Conn -> Positive Slope)", color='red')
    
    # 00s (High Connectivity)
    ax.text(df['ASF'].mean(), df['Basal_Corr'].max(), Z.min(), "Zone 2: Integration\n(High Conn -> Negative Slope)", color='green')
    
    fig.colorbar(surf, shrink=0.5, aspect=5)
    
    save_path = os.path.join(OUTPUT_DIR, 'Figure_Phase_Transition_3D.png')
    plt.savefig(save_path, dpi=300)
    print(f"Saved 3D Plot to {save_path}")

def main():
    try:
        df, coeffs = load_and_model()
        plot_surface(df, coeffs)
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
