name: caria-ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
      - run: poetry install --with dev
      - run: poetry run ruff check .
      - run: poetry run mypy src
      - run: poetry run pytest

